// Mock trace data for a coding agent solving a bug
window.TRACES = [
  {
    id: "trc_9f2a",
    title: "Fix: login redirect loop on SSO",
    repo: "acme/web",
    branch: "fix/sso-redirect",
    startedAt: "2026-04-20 14:22:08",
    duration: 47_210,
    totalTokens: 184_221,
    totalCost: 0.94,
    status: "running",
  },
  {
    id: "trc_8c1b",
    title: "Refactor: extract useAuth hook",
    repo: "acme/web",
    branch: "refactor/useauth",
    startedAt: "2026-04-20 13:01:44",
    duration: 92_140,
    totalTokens: 221_903,
    totalCost: 1.21,
    status: "done",
  },
  {
    id: "trc_7a33",
    title: "Add: CSV export for reports",
    repo: "acme/web",
    branch: "feat/csv-export",
    startedAt: "2026-04-20 11:45:19",
    duration: 151_330,
    totalTokens: 402_440,
    totalCost: 2.18,
    status: "done",
  },
  {
    id: "trc_6d90",
    title: "Investigate flaky test: payment.spec.ts",
    repo: "acme/web",
    branch: "main",
    startedAt: "2026-04-20 10:12:03",
    duration: 38_002,
    totalTokens: 88_410,
    totalCost: 0.31,
    status: "failed",
  },
];

// The active trace — a tree of LLM calls. Each node has parent reference.
// branches: array of alternate child sets explored by the user.
window.NODES = [
  {
    id: "n1",
    parent: null,
    kind: "plan",
    label: "understand task",
    model: "claude-sonnet-4.5",
    provider: "anthropic",
    tools: [],
    files: [],
    inputTokens: 1_204,
    outputTokens: 412,
    cost: 0.009,
    latency: 2140,
    ttft: 610,
    status: "ok",
    timestamp: "14:22:08",
    summary: "Form a plan to diagnose the SSO redirect loop.",
    decision: {
      goal: "Reproduce and locate the source of the redirect loop users hit after SSO callback.",
      options: [
        { label: "Read auth middleware first", chosen: true, reason: "Loop implies middleware is rejecting the session or cookie. Most likely culprit." },
        { label: "Start from the browser network tab", chosen: false, reason: "No repro env attached. Skip." },
        { label: "Grep for 'redirect' across repo", chosen: false, reason: "Too broad; likely hundreds of hits." },
      ],
      why: "Auth middleware is the narrowest scope given 'SSO callback → redirect loop' symptom.",
    },
    input: `<system>You are a coding agent. The user reports a redirect loop after SSO login on acme/web.</system>\n<user>After SSO, users land on /callback and bounce between /callback → /login → /callback forever. Fix it.</user>`,
    output: `I'll start by examining the auth middleware and SSO callback handler. Plan:\n1. Read src/middleware/auth.ts\n2. Read src/pages/auth/callback.ts\n3. Trace cookie/session lifecycle\n4. Identify where the loop originates\n5. Patch + add a regression test`,
    toolCalls: [],
  },
  {
    id: "n2",
    parent: "n1",
    kind: "tool",
    label: "search_fs",
    model: "claude-sonnet-4.5",
    provider: "anthropic",
    tools: ["search_fs"],
    files: [],
    inputTokens: 1_890,
    outputTokens: 220,
    cost: 0.008,
    latency: 1410,
    ttft: 480,
    status: "ok",
    timestamp: "14:22:11",
    summary: "Locate auth-related source files.",
    decision: {
      goal: "Find the files implementing auth middleware and SSO callback.",
      options: [
        { label: "glob src/**/auth*", chosen: true, reason: "Likely naming convention; fast." },
        { label: "semantic search 'session redirect'", chosen: false, reason: "Noisier; fallback if glob is empty." },
      ],
      why: "Glob is deterministic and cheap. Try it first.",
    },
    input: `Find files related to auth middleware and SSO callback.`,
    output: `Found:\n- src/middleware/auth.ts\n- src/pages/auth/callback.ts\n- src/pages/auth/login.ts\n- src/lib/session.ts`,
    toolCalls: [
      { name: "glob", args: { pattern: "src/**/auth*.{ts,tsx}" }, result: "4 matches in 42ms" },
    ],
  },
  {
    id: "n3",
    parent: "n2",
    kind: "tool",
    label: "read_file",
    model: "claude-sonnet-4.5",
    provider: "anthropic",
    tools: ["read_file"],
    files: ["src/middleware/auth.ts"],
    inputTokens: 2_410,
    outputTokens: 180,
    cost: 0.009,
    latency: 820,
    ttft: 410,
    status: "ok",
    timestamp: "14:22:13",
    summary: "Read auth middleware to inspect redirect logic.",
    decision: {
      goal: "Understand when middleware redirects to /login.",
      options: [{ label: "Read full file", chosen: true, reason: "File is small (<200 LOC)." }],
      why: "Full context avoids missing edge cases in a short file.",
    },
    input: "read_file(src/middleware/auth.ts)",
    output: "Returned 174 lines. Middleware checks session cookie 'sid' via isValidSession(); redirects to /login when missing or expired.",
    toolCalls: [{ name: "read_file", args: { path: "src/middleware/auth.ts" }, result: "174 lines" }],
  },
  {
    id: "n4",
    parent: "n3",
    kind: "llm",
    label: "analyze callback",
    model: "claude-sonnet-4.5",
    provider: "anthropic",
    tools: ["read_file"],
    files: ["src/pages/auth/callback.ts"],
    inputTokens: 3_820,
    outputTokens: 641,
    cost: 0.021,
    latency: 3_180,
    ttft: 720,
    status: "ok",
    timestamp: "14:22:17",
    highlighted: true,
    summary: "Identify bug: callback sets cookie with wrong domain.",
    decision: {
      goal: "Find why isValidSession() returns false immediately after SSO sets the cookie.",
      options: [
        { label: "Cookie set with wrong domain (subdomain mismatch)", chosen: true, reason: "Callback sets cookie on 'auth.acme.com' but app runs on 'app.acme.com'. Request to /middleware doesn't see the cookie → redirect to /login → SSO redirects back → loop." },
        { label: "Cookie TTL too short", chosen: false, reason: "Set to 24h; unlikely." },
        { label: "Session store eventually consistent", chosen: false, reason: "Using signed cookies, no remote store." },
        { label: "CSRF middleware strips cookie", chosen: false, reason: "CSRF runs after auth in the stack." },
      ],
      why: "Only the domain-mismatch hypothesis explains the loop *and* is consistent with the callback code on line 47 (`domain: '.auth.acme.com'`). The cookie is invisible to app.acme.com.",
    },
    input: `<tool_result>read_file(src/pages/auth/callback.ts): 98 lines\n...\n47:   cookies.set('sid', token, { domain: '.auth.acme.com', httpOnly: true, secure: true });\n...</tool_result>\n<user>Diagnose the loop.</user>`,
    output: `Found the bug. In src/pages/auth/callback.ts line 47, the session cookie is scoped to '.auth.acme.com' but the main app runs on 'app.acme.com'. After SSO, the cookie is dropped by the browser for the app subdomain, so auth middleware sees no session and redirects to /login → which redirects to SSO → which sets the cookie again on the wrong domain → loop.\n\nFix: change domain to '.acme.com' (parent domain) so both subdomains can read it.`,
    toolCalls: [{ name: "read_file", args: { path: "src/pages/auth/callback.ts" }, result: "98 lines" }],
  },
  {
    id: "n5",
    parent: "n4",
    kind: "tool",
    label: "edit_file",
    model: "claude-sonnet-4.5",
    provider: "anthropic",
    tools: ["edit_file"],
    files: ["src/pages/auth/callback.ts"],
    inputTokens: 4_102,
    outputTokens: 320,
    cost: 0.015,
    latency: 1_540,
    ttft: 510,
    status: "ok",
    timestamp: "14:22:21",
    summary: "Apply domain fix.",
    decision: {
      goal: "Change cookie domain from '.auth.acme.com' to '.acme.com'.",
      options: [{ label: "Single-line edit on line 47", chosen: true, reason: "Minimal, reviewable." }],
      why: "Smallest possible change to resolve the loop without touching unrelated logic.",
    },
    input: "apply patch to src/pages/auth/callback.ts",
    output: "Patched line 47. Diff: -domain: '.auth.acme.com' +domain: '.acme.com'",
    toolCalls: [{ name: "edit_file", args: { path: "src/pages/auth/callback.ts", line: 47 }, result: "1 line changed" }],
  },
  {
    id: "n6",
    parent: "n5",
    kind: "tool",
    label: "run_tests",
    model: "claude-sonnet-4.5",
    provider: "anthropic",
    tools: ["run_tests"],
    files: ["src/pages/auth/__tests__/callback.spec.ts"],
    inputTokens: 4_580,
    outputTokens: 210,
    cost: 0.011,
    latency: 8_720,
    ttft: 610,
    status: "ok",
    timestamp: "14:22:30",
    summary: "Run auth test suite.",
    decision: {
      goal: "Verify the fix doesn't break existing tests.",
      options: [{ label: "Run auth/** tests only", chosen: true, reason: "Scoped run is fast; full suite after." }],
      why: "Fast feedback loop first.",
    },
    input: "run_tests(src/pages/auth/**)",
    output: "14 passed, 0 failed, 1 skipped. Time: 8.1s.",
    toolCalls: [{ name: "run_tests", args: { glob: "src/pages/auth/**" }, result: "14 pass" }],
  },

  // --- Alternate branch A: different model explores the same step as n4 ---
  {
    id: "n4a",
    parent: "n3",
    kind: "llm",
    label: "analyze callback",
    model: "gpt-5",
    provider: "openai",
    tools: ["read_file"],
    files: ["src/pages/auth/callback.ts"],
    inputTokens: 3_820,
    outputTokens: 890,
    cost: 0.028,
    latency: 4_210,
    ttft: 880,
    status: "ok",
    timestamp: "14:28:02",
    isBranch: true,
    branchLabel: "another model",
    summary: "Alternate analysis with gpt-5.",
    decision: {
      goal: "Find why isValidSession() returns false after SSO sets the cookie.",
      options: [
        { label: "Cookie domain mismatch", chosen: true, reason: "Callback scopes cookie to '.auth.acme.com'; app is on 'app.acme.com'." },
        { label: "SameSite=Strict blocks cross-site redirect", chosen: false, reason: "Possible but only affects initial; loop would break differently." },
      ],
      why: "Same conclusion as main branch, but proposed a broader refactor of the cookie helper.",
    },
    input: `<tool_result>read_file(src/pages/auth/callback.ts): 98 lines...</tool_result>\n<user>Diagnose the loop.</user>`,
    output: `Root cause: cookie domain is '.auth.acme.com' on line 47, but the app runs under 'app.acme.com'. Recommend: (1) fix the domain on line 47 AND (2) extract a setSessionCookie() helper so this can't recur.`,
    toolCalls: [{ name: "read_file", args: { path: "src/pages/auth/callback.ts" }, result: "98 lines" }],
  },
  // --- Alternate branch B: new approach from the user ---
  {
    id: "n4b",
    parent: "n3",
    kind: "experiment",
    label: "new approach",
    model: "claude-opus-4",
    provider: "anthropic",
    tools: ["read_file", "search_fs"],
    files: ["src/pages/auth/callback.ts", "src/lib/cookies.ts"],
    inputTokens: 5_104,
    outputTokens: 1_210,
    cost: 0.065,
    latency: 6_840,
    ttft: 920,
    status: "ok",
    timestamp: "14:31:17",
    isBranch: true,
    branchLabel: "new approach",
    summary: "User asked: 'what if we centralize cookie config?'",
    decision: {
      goal: "Propose a refactor that prevents this class of bug entirely.",
      options: [
        { label: "Centralize cookie config in src/lib/cookies.ts with a single COOKIE_DOMAIN", chosen: true, reason: "Eliminates all site-specific cookie bugs." },
        { label: "Env variable SESSION_COOKIE_DOMAIN", chosen: false, reason: "Easy to misconfigure in staging." },
      ],
      why: "One source of truth is better than per-call domain strings.",
    },
    input: `<user>What if we centralize cookie config so this can't happen again?</user>`,
    output: `Proposal: create src/lib/cookies.ts exporting COOKIE_DOMAIN and setSessionCookie(token). Migrate callback.ts to use it. Adds ~40 LOC, removes 3 duplicated domain strings across the codebase.`,
    toolCalls: [
      { name: "search_fs", args: { pattern: "cookies.set|Set-Cookie" }, result: "3 matches" },
      { name: "read_file", args: { path: "src/lib/cookies.ts" }, result: "not found — new file" },
    ],
  },
];
