// Auto-generated by bin/scan-memories.mjs
// Source: /Users/dzmitryrekun/.claude/projects
// Generated: 2026-04-29T15:19:27.124Z
// To regenerate: node bin/scan-memories.mjs
window.MEMORY_GRAPH = {
  "nodes": [
    {
      "id": "proj:-Users-dzmitryrekun-github-neovim-bootcamp",
      "label": "github-neovim-bootcamp",
      "kind": "project",
      "folder": "-Users-dzmitryrekun-github-neovim-bootcamp",
      "memberCount": 1
    },
    {
      "id": "proj:-Users-dzmitryrekun-github-parallel",
      "label": "github-parallel",
      "kind": "project",
      "folder": "-Users-dzmitryrekun-github-parallel",
      "memberCount": 4
    },
    {
      "id": "mem:-Users-dzmitryrekun-github-neovim-bootcamp:project_neovim_bootcamp.md",
      "label": "Neovim bootcamp project scope",
      "kind": "memory",
      "type": "project",
      "description": "Personal project for practicing and configuring Neovim — learning workflow, keymaps, plugins",
      "body": "Personal Neovim learning/configuration project. Seed memory created 2026-04-29 to bootstrap the auto-memory file so the project shows up in the traceframe memory graph.\n\n**Why:** Without at least one memory file, `bin/scan-memories.mjs` skips the project entirely and it does not appear as a hub node in the graph UI.\n\n**How to apply:** Replace or augment this with real memories as the project develops — preferred plugins, keybinding choices, learning goals, things to avoid. This file can be deleted once organic memories accumulate.",
      "file": "project_neovim_bootcamp.md",
      "project": "-Users-dzmitryrekun-github-neovim-bootcamp",
      "projectLabel": "github-neovim-bootcamp"
    },
    {
      "id": "mem:-Users-dzmitryrekun-github-parallel:feedback_execution_flow.md",
      "label": "Plan → subagent-driven execution is the validated pattern",
      "kind": "memory",
      "type": "feedback",
      "description": "User picks the subagent-driven execution option every time — default to it when presenting a plan",
      "body": "For Parallel, the user has validated the brainstorming → spec → writing-plans → subagent-driven-development flow twice (data layer + API layer). When asked to choose between subagent-driven vs inline plan execution, they pick subagent-driven every time.\n\n**Why:** The plan is the coordination surface; each task gets a fresh subagent with isolated context, which kept both the 16-task data plan and the 24-task API plan green without handoff drift.\n\n**How to apply:**\n- When a plan is ready, still offer the choice once (skill requires it), but expect \"1.\" and prepare to dispatch immediately.\n- Keep the plan file itself detailed — future subagents dispatched with task text rely on it being complete.\n- If a subagent reports DONE but LSP later flags unused imports / deprecated helpers, fix inline with a small cleanup commit rather than redispatching. The user is tolerant of these small follow-ups.\n- Watch for subagents that **report a commit without actually staging files** — this happened once on Task 13 of the API plan. Verify the commit landed (`git show --stat HEAD`) before moving on, especially when tests pass (runtime reads from disk regardless of git state).",
      "file": "feedback_execution_flow.md",
      "project": "-Users-dzmitryrekun-github-parallel",
      "projectLabel": "github-parallel"
    },
    {
      "id": "mem:-Users-dzmitryrekun-github-parallel:project_parallel.md",
      "label": "Parallel project state and scope",
      "kind": "memory",
      "type": "project",
      "description": "What Parallel is, what ships, what's deliberately deferred",
      "body": "Parallel is a single-tenant-per-row freelancer command center — dashboard + Discover + Interviews + Cash + Contracts + CV screens. Repo at `/Users/dzmitryrekun/github/parallel`.\n\n**Shipped as of 2026-04-21:**\n\n- **Data layer** (20 Postgres tables, Kysely types, seed mapping UI hardcoded blocks into the schema, 52 tests).\n- **API layer** (Hono + zod + `@hono/node-server`, hybrid REST + view endpoints, typed `hc` client at `src/lib/api.ts`, 53 api tests).\n\n**Deliberately deferred, not bugs:**\n\n- **Auth.** The API identifies the caller via `process.env.DEV_OWNER_ID`. This was an explicit v1 choice (option A during brainstorming) to unblock end-to-end wiring. Real auth is a later plan.\n- **Pagination.** List endpoints return plain arrays. Spec describes `?limit=&cursor=`; the `PaginationQuerySchema` helper is scaffolded but unused.\n- **Discover ingestion worker.** `discover-listings` routes are read-only; the worker populates the table.\n- **File upload.** `/api/attachments` accepts metadata (`storage_key` or `external_url`) only; binary upload is a later concern.\n- **FX rate population worker.** Cash view handles missing rates gracefully (adds to `warnings`) rather than failing.\n\n**Why:** Keep: If UI is asking about behavior that looks missing in these areas, check this first before assuming a bug.\n\n**How to apply:** When reviewing gaps in the API or deciding what to build next, these are the known gaps — don't re-discover them as \"issues\", and don't propose work outside the next natural plan (UI wiring).\n\n**Likely next plan:** replace the hardcoded data blocks in `src/App.jsx` with real fetches via `client` from `src/lib/api.ts`. The UI file uses a single-file convention with `// === src/<name>.jsx ===` banners; don't split it without being asked (CLAUDE.md makes this explicit).",
      "file": "project_parallel.md",
      "project": "-Users-dzmitryrekun-github-parallel",
      "projectLabel": "github-parallel"
    },
    {
      "id": "mem:-Users-dzmitryrekun-github-parallel:reference_parallel_docs.md",
      "label": "Durable docs and external tooling for Parallel",
      "kind": "memory",
      "type": "reference",
      "description": "Where to find specs, plans, hot cache, log, and the configured Obsidian MCP",
      "body": "- **Specs:** `docs/superpowers/specs/YYYY-MM-DD-*.md` — approved architectural decisions. The HTML sibling (when present) is a rendered view, not the source of truth.\n- **Plans:** `docs/superpowers/plans/YYYY-MM-DD-*.md` — implementation plans driving subagent-driven-development. Each task is self-contained with full code; subagents are dispatched with task text from here.\n- **Hot cache:** `hot/hot.md` — rolling current-work surface. Updated at stopping points. If stale, the referenced file paths still hold but the \"what's next\" line may not.\n- **Chronological log:** `log.md` — append-only entries per day.\n- **Session notes:** `sessions/YYYY-MM-DD-*.md` — post-mortems with decisions/bugs/commits for large initiatives.\n\n**Obsidian MCP server** is already configured: `obsidian: uvx mcp-obsidian - ✓ Connected`. It reaches the vault at `/Users/dzmitryrekun/github/parallel` via the Local REST API plugin. Tools appear as `mcp__obsidian__*` when needed.\n\n**CLAUDE.md** at repo root is the authoritative source for project conventions (single-file `src/App.jsx` with module-banner structure, no test runner / linter configured, port 5174 strictPort, tweaks/edit-mode protocol via postMessage).",
      "file": "reference_parallel_docs.md",
      "project": "-Users-dzmitryrekun-github-parallel",
      "projectLabel": "github-parallel"
    },
    {
      "id": "mem:-Users-dzmitryrekun-github-parallel:user_working_style.md",
      "label": "User working style on Parallel",
      "kind": "memory",
      "type": "user",
      "description": "How the user likes to collaborate on the Parallel project — direct, auto mode, approve-and-execute",
      "body": "Solo developer shipping the Parallel freelancer command center end to end. Pattern across both shipped layers (data + API):\n\n- Uses auto mode for multi-hour execution and expects actual execution to happen without checking in.\n- Answers with single digits / terse confirmations (\"1.\", \"A\", \"lgtm\") when I present clear options. Don't over-explain — present the options, state a recommendation, stop.\n- When offered A/B/C, sometimes extends with an addition (e.g., \"A + docker compose\"). Treat this as a signal they want the capability, not a rejection of the option.\n- Prefers me to commit and update logs/hot cache at natural stopping points without asking.\n- Comfortable with technical depth — no need to gloss over trade-offs. Shorter is better than padded.",
      "file": "user_working_style.md",
      "project": "-Users-dzmitryrekun-github-parallel",
      "projectLabel": "github-parallel"
    }
  ],
  "edges": [
    {
      "source": "mem:-Users-dzmitryrekun-github-neovim-bootcamp:project_neovim_bootcamp.md",
      "target": "proj:-Users-dzmitryrekun-github-neovim-bootcamp",
      "kind": "member"
    },
    {
      "source": "mem:-Users-dzmitryrekun-github-parallel:feedback_execution_flow.md",
      "target": "proj:-Users-dzmitryrekun-github-parallel",
      "kind": "member"
    },
    {
      "source": "mem:-Users-dzmitryrekun-github-parallel:project_parallel.md",
      "target": "proj:-Users-dzmitryrekun-github-parallel",
      "kind": "member"
    },
    {
      "source": "mem:-Users-dzmitryrekun-github-parallel:reference_parallel_docs.md",
      "target": "proj:-Users-dzmitryrekun-github-parallel",
      "kind": "member"
    },
    {
      "source": "mem:-Users-dzmitryrekun-github-parallel:user_working_style.md",
      "target": "proj:-Users-dzmitryrekun-github-parallel",
      "kind": "member"
    }
  ]
};
